server:
   port: 8080
spring:
   application:
      name: starter
   datasource:
      driver-class-name: ${DATASOURCE_CLASSNAME}
      url: ${DATASOURCE_URL}
      username: ${DATASOURCE_USERNAME}
      password: ${DATASOURCE_PASSWORD}
   jpa:
      open-in-view: false
      show-sql: true
      hibernate:
         ddl-auto: validate
         format_sql: true 
      properties:
         hibernate:
            dialect: ${DATASOURCE_DIALECT}
   flyway:
      enabled: false
      location: classpath:db/migration
entitymanager:
   packagesToScan: com.virtusa.ls